### ISSUE TITLE
Crash in CopyTree if directory contains symlinks

### ISSUE THREAD

**Issue by d4s** [go-debos/fakemachine#11]
Crashed on initrd creation. This also stop Debos silently with error code = 0.

Crash log:
```
--- FAIL: TestSuccessfullCommand (0.00s)
panic: No handled [recovered]
    panic: No handled

goroutine 5 [running]:
panic(0x64b6a0, 0xc4200e6570)
    /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420086180)
    /usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x64b6a0, 0xc4200e6570)
    /usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/go-debos/fakemachine/cpio.(*WriterHelper).CopyTree.func1(0xc420015680, 0x2b, 0x7bdc60, 0xc4200f0750, 0x0, 0x0, 0x0, 0x0)
    /home/fredo/Documents/bos0009/go/src/github.com/go-debos/fakemachine/cpio/writerhelper.go:112 +0x141
path/filepath.walk(0xc420015680, 0x2b, 0x7bdc60, 0xc4200f0750, 0xc4200e6350, 0x0, 0x0)
    /usr/lib/go-1.7/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x6ab2ea, 0x11, 0x7bdc60, 0xc4200f01a0, 0xc4200e6350, 0x0, 0x1)
    /usr/lib/go-1.7/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0x6ab2ea, 0x11, 0xc4200e6350, 0xf, 0x0)
    /usr/lib/go-1.7/src/path/filepath/path.go:398 +0xd5
github.com/go-debos/fakemachine/cpio.(*WriterHelper).CopyTree(0xc42000d5b0, 0x6ab2ea, 0x11)
    /home/fredo/Documents/bos0009/go/src/github.com/go-debos/fakemachine/cpio/writerhelper.go:118 +0x79
github.com/go-debos/fakemachine.(*Machine).startup(0xc420088400, 0x6a7933, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/fredo/Documents/bos0009/go/src/github.com/go-debos/fakemachine/machine.go:426 +0x83d
```
```
fredo@i7:~/Documents/bos0009/go/src/github.com/go-debos/fakemachine$ ls -l /etc/ld.so.conf.d/
total 20
-rw-r--r-- 1 root root 38 août  12  2016 fakeroot-x86_64-linux-gnu.conf
-rw-r--r-- 1 root root 44 janv. 27  2016 libc.conf
-rw-r--r-- 1 root root 68 oct.   5  2016 x86_64-linux-gnu.conf
lrwxrwxrwx 1 root root 43 janv.  8  2017 x86_64-linux-gnu_EGL.conf -> /etc/alternatives/x86_64-linux-gnu_egl_conf
lrwxrwxrwx 1 root root 42 janv. 12  2017 x86_64-linux-gnu_GL.conf -> /etc/alternatives/x86_64-linux-gnu_gl_conf
-rw-r--r-- 1 root root 56 nov.  16  2016 zz_i386-biarch-compat.conf
-rw-r--r-- 1 root root 58 nov.  16  2016 zz_x32-biarch-compat.conf
```

**Comment by d4s** [comment]
Duplicate of #12
