### ISSUE TITLE
fakemachine crash on ubuntu

### ISSUE THREAD

**Issue by Thread974** [go-debos/fakemachine#12]
Seeing the following crash.
```
--- FAIL: TestSuccessfullCommand (0.00s)
panic: No handled [recovered]
	panic: No handled

goroutine 5 [running]:
panic(0x64b6a0, 0xc4200f6570)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094180)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x64b6a0, 0xc4200f6570)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/go-debos/fakemachine/cpio.(*WriterHelper).CopyTree.func1(0xc420015680, 0x2b, 0x7bdc60, 0xc4200f4820, 0x0, 0x0, 0x0, 0x0)
	github.com/go-debos/fakemachine/cpio/writerhelper.go:112 +0x141
path/filepath.walk(0xc420015680, 0x2b, 0x7bdc60, 0xc4200f4820, 0xc4200f6350, 0x0, 0x0)
	/usr/lib/go-1.7/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x6ab2ea, 0x11, 0x7bdc60, 0xc4200f4270, 0xc4200f6350, 0x0, 0x1)
	/usr/lib/go-1.7/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0x6ab2ea, 0x11, 0xc4200f6350, 0xf, 0x0)
	/usr/lib/go-1.7/src/path/filepath/path.go:398 +0xd5
github.com/go-debos/fakemachine/cpio.(*WriterHelper).CopyTree(0xc42000d5b0, 0x6ab2ea, 0x11)
	github.com/go-debos/fakemachine/cpio/writerhelper.go:118 +0x79
github.com/go-debos/fakemachine.(*Machine).startup(0xc420096400, 0x6a7933, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/go-debos/fakemachine/machine.go:426 +0x83d
github.com/go-debos/fakemachine.(*Machine).Run(0xc420096400, 0x6a7933, 0x4, 0x5a032262, 0x2e298c0f, 0xc42002ff78)
	github.com/go-debos/fakemachine/machine.go:539 +0x5a
github.com/go-debos/fakemachine.TestSuccessfullCommand(0xc420094180)
	github.com/go-debos/fakemachine/machine_test.go:16 +0x48
testing.tRunner(0xc420094180, 0x6cacc0)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/go-debos/fakemachine	0.007s
```

There appears to be symlinks in the /etc/ls.so.conf.d/ directory and those make

**Comment by d4s** [comment]
Some distros have compiled-in kernel modules like ubuntu: `CONFIG_VIRTIO=y`
Need confirurable modules list or simple analysis of kernel config.

**Comment by Thread974** [comment]
ubuntu kernel has the following modules builtin :
* "kernel/drivers/virtio/virtio.ko",
* "kernel/drivers/virtio/virtio_pci.ko",
* "kernel/drivers/virtio/virtio_ring.ko",

And the kernel permissions are :
-rw------- 1 root root  7583504 oct.   6 21:45 vmlinuz-4.10.0-37-generic

**Comment by sjoerdsimons** [comment]
The kernel not being readable by a normal user does completely break the basic idea behind fakemachine, so that's not really something we can nicely support.

**Comment by d4s** [comment]
Fail into that issue trying to copy the content of `/etc/ld.so.conf.d` containing symlinks:
```
$ ls -l /etc/ld.so.conf.d
total 20
-rw-rw-r-- 1 root root 38 Sep 16 07:26 fakeroot-x86_64-linux-gnu.conf
-rw-r--r-- 1 root root 44 Sep  4 20:23 libc.conf
-rw-r--r-- 1 root root 68 Nov 12 11:22 x86_64-linux-gnu.conf
lrwxrwxrwx 1 root root 43 Jan  6 19:01 x86_64-linux-gnu_EGL.conf -> /etc/alternatives/x86_64-linux-gnu_egl_conf
lrwxrwxrwx 1 root root 42 Jan  6 19:01 x86_64-linux-gnu_GL.conf -> /etc/alternatives/x86_64-linux-gnu_gl_conf
```

additional effect of that issue: `debos` silently do nothing with return code `0`.

**Comment by obbardc** [comment]
Tracked by Ubuntu on launchpad: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725
